Feature: update frontier
UniqueNetwork/unique-frontier pull request #10
Opened 2022-10-18 08:05 UTC by fairax

2022-10-18 08:41 UTC, CertainLach requested changes
Пока ничего критичного не нашёл, позже буду срввнивать то что вышло, с тем что в апстриме для надёжности
Кактя вижу, в новом фронтире переделали систему валидации и оплаты транзакций, надо бы наш код оплаты (спонсирования) перевести в реализацию её трейтов

2022-10-18 08:41 UTC, CertainLach commented on frame/evm/src/lib.rs
> +		/// Weight corresponding to a gas unit.
Это не то же самое, что и GasWeightMapping?

2022-10-18 08:41 UTC, CertainLach commented on frame/evm/src/runner/stack.rs
> +		let fee = T::OnChargeTransaction::withdraw_fee(sponsor, reason, total_fee)
По идее с новой логикой мы можем всю поддержку спонсирования перевести в OnChargeTransaction, или где-то ещё требуется TransactionValidityHack напрямую?

2022-10-18 13:16 UTC, fairax commented on frame/evm/src/lib.rs
> +		/// Weight corresponding to a gas unit.
`WeightPerGas` это коэффициэнт, а `GasWeightMapping` это методы для конвертирования, использующие этот коэффициэнт. Или в чём вопрос?

2022-10-18 13:21 UTC, CertainLach commented on frame/evm/src/lib.rs
> +		/// Weight corresponding to a gas unit.
Я не понимаю почему тут используются оба)
В апстриме аналогично?

2022-10-19 06:23 UTC, fairax commented on frame/evm/src/lib.rs
> +		/// Weight corresponding to a gas unit.
Да, это код из апстрима без изменений.

2022-11-16 07:55 UTC, closed without merging