Move sponsorship logic to chain
UniqueNetwork/unique-frontier pull request #14
Opened 2023-04-10 10:28 UTC by bugrazoid

2023-04-18 12:57 UTC, CertainLach requested changes

2023-04-18 12:57 UTC, CertainLach commented on primitives/evm/src/lib.rs
> +		is_check: bool,
is_check сдесь лишний, его стоит где-то сбоку пробрасывать, чтобы WithdrawReason можно было переиспользовать.
По хорошему в нашей pallet-sponsoring стоит разнести методы проверки и обновления, но это потом

2023-04-18 12:57 UTC, CertainLach commented on template/runtime/src/lib.rs
> +	type TransactionValidityOnChain<E: From<pallet_evm::InvalidEvmTransactionError>> = ();
Просто TrasnsactionValidity, т.к этот трейт и при валидации в пуле участвует

2023-04-18 12:57 UTC, CertainLach commented on template/runtime/src/lib.rs
>  	type OnCreate = ();
Нужен ребейз, OnCreate ушёл в апстрим, и кроме него в апстриме есть несколько крупных изменений логики оплаты

2023-04-18 12:57 UTC, CertainLach commented on primitives/evm/src/lib.rs
> +		is_check: bool,
Возможно вместо WithdrawReason можно передавать прямо транзакцию/CheckEvmTransaction/CheckEvmTransactionInput? Хотелось бы избавиться от этого енама когда будем заносить в апстрим, т.к со стороны evm это не очень корректное разнесение на категории транзакций

2023-04-18 12:57 UTC, CertainLach commented on frame/evm/src/runner/stack.rs
> +		let v = T::TransactionValidityOnChain::<Error<T>>::check_evm_transaction(v, &source)
`.and_then(|v| T::TransactionValidityOnChain::...)`

2023-04-18 12:57 UTC, CertainLach commented on frame/evm/src/lib.rs
> +		origin: &T::CrossAccountId,
origin != v.who?

2023-04-18 12:57 UTC, CertainLach commented on frame/evm/src/runner/stack.rs
> +			source_account,
Не лучше ли перенести source_account в CheckEvmTransactionInput?

2023-05-15 09:22 UTC, bugrazoid commented on frame/evm/src/lib.rs
> +		origin: &T::CrossAccountId,
Это разные типы

2023-05-15 09:57 UTC, bugrazoid commented on frame/evm/src/runner/stack.rs
> +		let v = T::TransactionValidityOnChain::<Error<T>>::check_evm_transaction(v, &source)
Не на чем вызывать and_then.

2023-05-15 10:21 UTC, bugrazoid commented on frame/evm/src/runner/stack.rs
> +			source_account,
Можно, но это надо будет лезть в крейт ethereum (преобразование CheckEvmTransactionInput из LegacyTransaction), я думаю это лишнее.

2023-09-20 08:14 UTC, closed without merging