Move sponsorship logic to chain
UniqueNetwork/unique-frontier pull request #17
Opened 2023-06-28 12:55 UTC by fairax

2023-06-29 08:19 UTC, CertainLach requested changes

2023-06-29 08:19 UTC, CertainLach commented on frame/ethereum/src/lib.rs
> +		if transaction_nonce > v.who.nonce {
Возможность переопределять нонс в проверке транзакции явно лишнее, нонс нужно у отправителя транзакции смотреть/обновлять

2023-06-29 08:19 UTC, CertainLach commented on frame/evm/src/lib.rs
> +		origin: &H160,
Отправитель доступен из v, передавать его тут избыточно я думаю

2023-06-29 11:16 UTC, fairax commented on frame/evm/src/lib.rs
> +		origin: &H160,
Как его достать из `v`? Там вроде только `who` есть, который содержит nonce и balance.

2023-06-29 11:22 UTC, CertainLach commented on frame/evm/src/lib.rs
> +		origin: &H160,
А, действительно, он же заранее прогружен

2023-06-30 13:10 UTC, CertainLach requested changes

2023-06-30 13:10 UTC, CertainLach commented on primitives/evm/src/lib.rs
> +pub enum WithdrawReason {
Применимо возражение что и к коду Сергея - нужно убрать, это не совсем так должно работать в семантике эфира.
Можно оплату спонсирования (OnChargeEVMTransaction) вынести в отдельный патч, и себе пока оставить WithdrawReason, но в апстрим оно так не попадёт.

2023-07-03 07:47 UTC, fairax commented on primitives/evm/src/lib.rs
> +pub enum WithdrawReason {
Я разделил OnChargeEVMTransaction и WithdrawReason на отдельные коммиты.

2023-09-20 08:13 UTC, CertainLach commented
Я так понимаю что актуальная версия это то что идёт в апстрим, и пр в апстрим нужно отребейзить на наши patches

2023-09-20 14:40 UTC, closed without merging