Update patches for polkadot 0.9.43
UniqueNetwork/unique-frontier pull request #18
Opened 2023-07-07 08:52 UTC by fairax

2023-07-07 08:54 UTC, fairax commented on client/db/Cargo.toml
> +frontier-template-runtime = { workspace = true, features = ["default"] }
Добавил чтобы починить проблему с новыми тестами из `[sql backend w/ receipt log indexing](https://github.com/paritytech/frontier/pull/883/files#top)`

2023-07-07 08:56 UTC, fairax commented on frame/evm/src/runner/stack.rs
> +		{
Переделал метод из-за изменений в прекомпайлах

2023-07-07 09:13 UTC, CertainLach commented
Последние 2 патча (value + fix transfer) стоит засквошить/заfixupить
С первыми двумя (версия+фиксы) нужно поступить аналогично

2023-07-07 09:14 UTC, CertainLach requested changes

2023-07-07 09:14 UTC, CertainLach commented on frame/evm/precompile/dispatch/src/mock.rs
> +	pub const ExistentialDeposit: u64 = 1;
А зачем? Разве в тестах не включён insecure_zero_ed?

2023-07-07 09:14 UTC, CertainLach commented on frame/ethereum/src/mock.rs
> +		AccountId32::from(data)
Конверсия из эфира в субстрат каноничная это HashedAddressMapping.
Я не вижу где бы мы пользовались этим конвертером, но его в любом случае стоит убрать как некорректный

2023-07-07 09:23 UTC, fairax commented on frame/evm/precompile/dispatch/src/mock.rs
> +	pub const ExistentialDeposit: u64 = 1;
Это уже было в патчах. Можно попробовать переделать.

2023-07-07 11:56 UTC, fairax commented on frame/evm/precompile/dispatch/src/mock.rs
> +	pub const ExistentialDeposit: u64 = 1;
Убрал

2023-07-07 14:13 UTC, CertainLach commented on client/db/Cargo.toml
> +frontier-template-runtime = { workspace = true, features = ["default"] }
Я не вижу в тестах использования рантайма, можно подробнее?

2023-07-07 14:14 UTC, CertainLach commented on client/db/Cargo.toml
> +frontier-template-runtime = { workspace = true, features = ["default"] }
Вернее, я вижу
let (client, _) =
			builder.build_with_native_executor::<frontier_template_runtime::RuntimeApi, _>(None);
Но не понимаю зачем нам там использовать именно рантайм

2023-07-10 07:58 UTC, fairax commented on client/db/Cargo.toml
> +frontier-template-runtime = { workspace = true, features = ["default"] }
У нас добавились констреинты для `SchemaV3Override`
`C: ProvideRuntimeApi<B>,
C::Api: EthereumRuntimeRPCApi<B>`
Чтобы они выполнялись понадобился другой рантайм.

2023-07-10 08:32 UTC, CertainLach approved these changes

2023-07-10 08:32 UTC, merged